"""Web search tool backed by the Tavily API."""

import os
from typing import Any

import requests

from src.agent.interfaces import ToolInterface


class WebSearchTool(ToolInterface):
    """Search the internet for information relevant to an agent's task."""

    def __init__(
        self,
        api_key: str | None = None,
        max_results: int = 3,
    ) -> None:
        # None uses the environment; an explicit empty key disables Tavily.
        self.api_key = (
            os.environ.get("TAVILY_API_KEY", "") if api_key is None else api_key
        ).strip()

        if not 1 <= max_results <= 20:
            raise ValueError("max_results must be between 1 and 20.")

        self.max_results = max_results
        self.endpoint = "https://api.tavily.com/search"

    @property
    def name(self) -> str:
        return "web_search"

    @property
    def description(self) -> str:
        return (
            "Search the internet for up-to-date football news, transfers, "
            "match results, and recent events. "
            "Argument: 'query' (str) - search query text."
        )

    @property
    def parameters(self) -> dict[str, Any]:
        """Describe the arguments the LLM can supply to this tool."""
        return {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "The search query to look up.",
                }
            },
            "required": ["query"],
        }

    def run(self, arguments: dict[str, Any] | str | None = None, **kwargs: Any) -> str:
        """Submit a search and return readable results."""
        params: dict[str, Any] = {}
        if isinstance(arguments, dict):
            params.update(arguments)
        elif isinstance(arguments, str) and arguments.strip():
            params["query"] = arguments.strip()
        params.update(kwargs)

        queries_to_run: list[str] = []
        # Check query field
        if "query" in params:
            val = params["query"]
            if isinstance(val, str) and val.strip():
                queries_to_run.append(val.strip())
            elif isinstance(val, list):
                queries_to_run.extend(item.strip() for item in val if isinstance(item, str) and item.strip())

        # Check queries field (frequently generated by Gemini when examining multiple claims)
        if "queries" in params:
            val = params["queries"]
            if isinstance(val, list):
                queries_to_run.extend(item.strip() for item in val if isinstance(item, str) and item.strip())
            elif isinstance(val, str) and val.strip():
                queries_to_run.append(val.strip())

        # Check alternative keys
        for alt_key in ("search_query", "q", "expression"):
            if not queries_to_run and alt_key in params:
                val = params[alt_key]
                if isinstance(val, str) and val.strip():
                    queries_to_run.append(val.strip())

        if not queries_to_run:
            raise ValueError(
                "web_search requires a non-empty string 'query' argument."
            )

        # Deduplicate queries while preserving order
        seen = set()
        unique_queries = []
        for q in queries_to_run:
            if q not in seen:
                seen.add(q)
                unique_queries.append(q)

        all_results = []
        for q in unique_queries[:2]:  # Limit to 2 queries per call to stay within latency and rate limits
            res = self._search_single_query(q)
            if res and not res.startswith("Error"):
                all_results.append(res)
            elif res and not all_results:
                all_results.append(res)

        return "\n---\n".join(all_results) if all_results else "No web search results found."

    def _search_single_query(self, query: str) -> str:
        """Execute search for a single query string using Tavily or DuckDuckGo."""
        if self.api_key:
            try:
                headers = {
                    "Authorization": f"Bearer {self.api_key}",
                }
                payload = {
                    "query": query.strip(),
                    "search_depth": "basic",
                    "max_results": self.max_results,
                    "include_answer": True,
                }
                response = requests.post(
                    self.endpoint,
                    headers=headers,
                    json=payload,
                    timeout=20,
                )
                response.raise_for_status()
                data = response.json()

                formatted_results = []
                if data.get("answer"):
                    formatted_results.append(
                        f"Tavily-generated summary: {data['answer']}"
                    )

                for result in data.get("results", []):
                    formatted_results.append(
                        f"Title: {result.get('title', '')}\n"
                        f"URL: {result.get('url', '')}\n"
                        f"Content: {result.get('content', '')}"
                    )

                if formatted_results:
                    return "\n---\n".join(formatted_results)
            except Exception:
                # Fall back to DuckDuckGo search if Tavily fails or times out
                pass

        return self._duckduckgo_search(query.strip())

    def _duckduckgo_search(self, query: str) -> str:
        """Search the web using DuckDuckGo (no API key required)."""
        import time
        try:
            try:
                from ddgs import DDGS
            except ImportError:
                from duckduckgo_search import DDGS

            results = []
            for attempt in range(2):
                try:
                    results = list(DDGS().text(query, max_results=self.max_results))
                    break
                except Exception as e:
                    if attempt == 0 and ("202" in str(e) or "ratelimit" in str(e).lower()):
                        time.sleep(1.0)
                        continue
                    raise
            if not results:
                return f"No external web search results found for '{query}'. Proceed with tactical match analysis."
            formatted = []
            for r in results:
                title = r.get("title", "")
                url = r.get("href") or r.get("url", "")
                snippet = r.get("body") or r.get("content", "")
                formatted.append(f"Title: {title}\nURL: {url}\nContent: {snippet}")
            return "\n---\n".join(formatted)
        except Exception as err:
            raise RuntimeError("Web search failed after provider fallback.") from err
